language: java
sudo: required
jdk: openjdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean install
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push microportal/portal-service
