language: java
sudo: required
jdk: openjdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - mvn clean install
  - docker push microportal/portal-service
