language: java
sudo: required
jdk: openjdk11

services:
  - docker

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean install

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push microportal/portal-service
  on:
    branch: master